// <auto-generated />
using AspNetWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetWebApi.Migrations
{
    [DbContext(typeof(AnimalContext))]
    [Migration("20181128224122_CreateTables")]
    partial class CreateTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspNetWebApi.Data.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LivesInId");

                    b.Property<string>("Name");

                    b.Property<int>("NumberOfLegs");

                    b.HasKey("Id");

                    b.HasIndex("LivesInId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LivesInId = 1,
                            Name = "Dog",
                            NumberOfLegs = 4
                        },
                        new
                        {
                            Id = 2,
                            LivesInId = 2,
                            Name = "Cat",
                            NumberOfLegs = 4
                        },
                        new
                        {
                            Id = 3,
                            LivesInId = 3,
                            Name = "Sloth",
                            NumberOfLegs = 2
                        });
                });

            modelBuilder.Entity("AspNetWebApi.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "England"
                        },
                        new
                        {
                            Id = 2,
                            Name = "France"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Germany"
                        });
                });

            modelBuilder.Entity("AspNetWebApi.Data.Animal", b =>
                {
                    b.HasOne("AspNetWebApi.Data.Country", "LivesIn")
                        .WithMany()
                        .HasForeignKey("LivesInId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
