// <auto-generated />
using System;
using AspNetWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace AspNetWebApi.Migrations
{
    [DbContext(typeof(AnimalContext))]
    // ReSharper disable once UnusedMember.Global
    internal class AnimalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspNetWebApi.Data.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnimalType");

                    b.Property<int>("LivesInId");

                    b.Property<string>("Name");

                    b.Property<short>("NumberOfLegs");

                    b.HasKey("Id");

                    b.HasIndex("LivesInId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalType = 0,
                            LivesInId = 1,
                            Name = "Dog",
                            NumberOfLegs = (short)4
                        },
                        new
                        {
                            Id = 2,
                            AnimalType = 0,
                            LivesInId = 2,
                            Name = "Cat",
                            NumberOfLegs = (short)4
                        },
                        new
                        {
                            Id = 3,
                            AnimalType = 0,
                            LivesInId = 3,
                            Name = "Sloth",
                            NumberOfLegs = (short)2
                        },
                        new
                        {
                            Id = 4,
                            AnimalType = 1,
                            LivesInId = 4,
                            Name = "Snake",
                            NumberOfLegs = (short)0
                        });
                });

            modelBuilder.Entity("AspNetWebApi.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "England"
                        },
                        new
                        {
                            Id = 2,
                            Name = "France"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Australia"
                        });
                });

            modelBuilder.Entity("AspNetWebApi.Data.CountryProperties", b =>
                {
                    b.Property<int>("CountryId");

                    b.Property<bool>("HasMonarchy");

                    b.Property<DateTime?>("LastTimeWonWorldCup");

                    b.Property<long>("Population");

                    b.Property<decimal>("TaxRate");

                    b.HasKey("CountryId");

                    b.ToTable("CountryProperties");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            HasMonarchy = true,
                            LastTimeWonWorldCup = new DateTime(1966, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Population = 55619400L,
                            TaxRate = 0.2m
                        },
                        new
                        {
                            CountryId = 2,
                            HasMonarchy = false,
                            LastTimeWonWorldCup = new DateTime(2018, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Population = 67348000L,
                            TaxRate = 0.2m
                        },
                        new
                        {
                            CountryId = 3,
                            HasMonarchy = true,
                            LastTimeWonWorldCup = new DateTime(2014, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Population = 82800000L,
                            TaxRate = 0.19m
                        },
                        new
                        {
                            CountryId = 4,
                            HasMonarchy = true,
                            Population = 25155300L,
                            TaxRate = 0.1m
                        });
                });

            modelBuilder.Entity("AspNetWebApi.Data.Animal", b =>
                {
                    b.HasOne("AspNetWebApi.Data.Country", "LivesIn")
                        .WithMany("Animals")
                        .HasForeignKey("LivesInId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspNetWebApi.Data.CountryProperties", b =>
                {
                    b.HasOne("AspNetWebApi.Data.Country", "Country")
                        .WithOne("CountryProperties")
                        .HasForeignKey("AspNetWebApi.Data.CountryProperties", "CountryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
